import Navbar from "@/components/Navbar";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-mont" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, className = "" }) {
	return (
		<html lang="en">
			<body className={`font-mont bg-light`}>
				<Navbar />
				<div className={`p-32 inline-block z-0 w-full min-h-screen ${className}`}>
					{children}
				</div>
			</body>
		</html>
	);
}
