import Photo1 from "@/public/images/photos/07_15_2023-05590.webp";

export const items = [
	{
		id: 1,
		url: "/images/photos/09_03_2022-02496.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 2,
		url: "/images/photos/09_03_2022-02698.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 3,
		url: "/images/photos/09_05_2022-03030.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 4,
		url: "/images/photos/09_05_2022-03057.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 5,
		url: "/images/photos/09_05_2022-03140.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 6,
		url: "/images/photos/09_05_2022-03141.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 7,
		url: "/images/photos/09_06_2022-03157.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 8,
		url: "/images/photos/09_17_2022-03275.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 9,
		url: "/images/photos/09_17_2022-03332.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 10,
		url: "/images/photos/09_17_2022-03541.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 11,
		url: "/images/photos/09_17_2022-03607.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 12,
		url: "/images/photos/06_03_2023-05154.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 13,
		url: "/images/photos/07_01_2023-05297.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 14,
		url: "/images/photos/07_15_2023-05518.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 15,
		url: "/images/photos/07_15_2023-05590.webp",
		title: "Lorem ipsum",
		description: "Lorem ipsum dolor",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
];
