import Photo1 from "@/public/images/photos/07_15_2023-05590.webp";

export const items = [
	{
		id: 1,
		url: "/images/photos/09_03_2022-02496.webp",
		title: "Photo-1",
		location: "Vila Nova de Milfontes, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 2,
		url: "/images/photos/09_03_2022-02698.webp",
		title: "Photo-2",
		location: "Lagos, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 3,
		url: "/images/photos/09_05_2022-03030.webp",
		title: "Photo-3",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 4,
		url: "/images/photos/09_05_2022-03057.webp",
		title: "Photo-4",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 5,
		url: "/images/photos/09_05_2022-03140.webp",
		title: "Photo-5",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 6,
		url: "/images/photos/09_05_2022-03141.webp",
		title: "Photo-6",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 7,
		url: "/images/photos/09_06_2022-03157.webp",
		title: "Photo-7",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 8,
		url: "/images/photos/09_17_2022-03275.webp",
		title: "Photo-8",
		location: "Assenta, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 16,
		url: "/images/photos/04_09_2023-04686.webp",
		title: "Photo-9",
		location: "Sintra Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 9,
		url: "/images/photos/09_17_2022-03332.webp",
		title: "Photo-10",
		location: "Assenta, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 10,
		url: "/images/photos/09_17_2022-03541.webp",
		title: "Photo-11",
		location: "Assenta, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 11,
		url: "/images/photos/09_17_2022-03607.webp",
		title: "Photo-12",
		location: "Assenta, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 12,
		url: "/images/photos/06_03_2023-05154.webp",
		title: "Photo-13",
		location: "Ericeira, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 13,
		url: "/images/photos/07_01_2023-05297.webp",
		title: "Photo-14",
		location: "Estremoz, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 14,
		url: "/images/photos/07_15_2023-05518.webp",
		title: "Photo-15",
		location: "Tancos, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 15,
		url: "/images/photos/07_15_2023-05590.webp",
		title: "Almourol Castle",
		location: "Tancos, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
];
