import Photo1 from "@/public/images/photos/07_15_2023-05590.webp";

export const items = [
	{
		id: 1,
		url: "/images/photos/09_03_2022-02496.webp",
		title: "Photo-1",
		location: "Vila Nova de Milfontes, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 2,
		url: "/images/photos/09_03_2022-02698.webp",
		title: "Photo-2",
		location: "Lagos, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 3,
		url: "/images/photos/09_05_2022-03030.webp",
		title: "Photo-3",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 4,
		url: "/images/photos/09_05_2022-03057.webp",
		title: "Photo-4",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 5,
		url: "/images/photos/09_05_2022-03140.webp",
		title: "Photo-5",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 6,
		url: "/images/photos/09_05_2022-03141.webp",
		title: "Photo-6",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 7,
		url: "/images/photos/09_06_2022-03157.webp",
		title: "Photo-7",
		location: "Odeceixe, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 8,
		url: "/images/photos/09_17_2022-03275.webp",
		title: "Photo-8",
		location: "Assenta, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 16,
		url: "/images/photos/04_09_2023-04686.webp",
		title: "Photo-9",
		location: "Sintra Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 9,
		url: "/images/photos/09_17_2022-03332.webp",
		title: "Photo-10",
		location: "Assenta, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 10,
		url: "/images/photos/09_17_2022-03541.webp",
		title: "Photo-11",
		location: "Assenta, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 11,
		url: "/images/photos/09_17_2022-03607.webp",
		title: "Photo-12",
		location: "Assenta, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 12,
		url: "/images/photos/06_03_2023-05154.webp",
		title: "Photo-13",
		location: "Ericeira, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 13,
		url: "/images/photos/07_01_2023-05297.webp",
		title: "Photo-14",
		location: "Estremoz, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 14,
		url: "/images/photos/07_15_2023-05518.webp",
		title: "Photo-15",
		location: "Tancos, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
	{
		id: 15,
		url: "/images/photos/07_15_2023-05590.webp",
		title: "Almourol Castle",
		location: "Tancos, Portugal",
		tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
	},
];

export const projects = [
	{
		name: "SoulDance Studio",
		punchline:
			"The SoulDance Studio website serves as a vibrant gateway to explore the world of dance, offering a captivating platform to discover classes, events, and unleash the joy of movement.",
		description:
			"The construction of the SoulDance website involved a comprehensive and efficient development process, employing modern web technologies to deliver a captivating user experience. Initially, thorough planning and wireframing were carried out to conceptualize the site's layout and features. NextJs was chosen as the framework due to its server-side rendering capabilities and seamless integration with React, which allowed for fast-loading, SEO-friendly pages. React, being the primary library, facilitated the creation of interactive and dynamic components that enhanced user engagement. Tailwind CSS was selected for styling, enabling a responsive and visually appealing design, with the utility-first approach streamlining the development process. For the backend and database, Sanity was employed, empowering the team to manage content effortlessly and efficiently. Overall, this combination of React, NextJs, Tailwind CSS, and Sanity provided the foundation for a modern, responsive, and user-friendly website for SoulDance, catering to their unique needs and delighting visitors with a seamless dance experience.",
		image: "/images/projects/projects-souldance.webp",
		stack: {
			library: "React.js",
			framework: "Next.js",
			buildTool: null,
			styling: ["Tailwind"],
			cms: "Sanity",
			database: null,
			backend: null,
			others: ["Photoshop", "Illustrator"],
		},
		githubLink: "https://github.com/andregn26/next-souldance",
		isLive: false,
		liveLink: "",
	},
	{
		name: "Travel Advisor",
		punchline:
			"Travel Advisor is a web application built with the purpose of helping people discover the best restaurants, hotels, and points of interest in their geographic area or around the globe. The project is designed to provide users with an intuitive and seamless experience in finding top-notch locations for their travels.",
		description:
			"Lorem ipsum dolor sit amet. Et molestias voluptas sed nemo mollitia non galisum sunt a eius earum qui similique eligendi eum optio iure et optio molestias. Est obcaecati numquam sed dolorum suscipit et autem facilis et quibusdam voluptas ea cumque pariatur. Ea aliquam dolorum non exercitationem aspernatur est voluptatibus dolor.",
		image: "/images/projects/projects-travel-advisor.webp",
		stack: {
			library: "React.js",
			framework: null,
			buildTool: "Vite",
			styling: ["Material UI", "Styled Components"],
			cms: null,
			database: null,
			backend: null,
			others: null,
		},
		githubLink: "https://github.com/andregn26/travel-companion-application",
		isLive: true,
		liveLink: "https://travel-companion-application.vercel.app/",
	},
	{
		name: "Corporate Dashboard",
		punchline:
			"A dashboard that provides an easy to use interface for employees to view and manage important company information, such as sales data, employee information, and performance metrics.",
		description:
			"Lorem ipsum dolor sit amet. Et molestias voluptas sed nemo mollitia non galisum sunt a eius earum qui similique eligendi eum optio iure et optio molestias. Est obcaecati numquam sed dolorum suscipit et autem facilis et quibusdam voluptas ea cumque pariatur. Ea aliquam dolorum non exercitationem aspernatur est voluptatibus dolor.",
		image: "/images/projects/projects-corp_dashboard.webp",
		stack: {
			library: "React.js",
			framework: null,
			buildTool: "CRA",
			styling: ["Material UI"],
			cms: null,
			database: "MongoDB",
			backend: "Express",
			others: ["Nivo", "Redux", "Date-picker"],
		},
		githubLink: "https://github.com/andregn26/corporate-dashboard",
		isLive: true,
		liveLink: "https://insightiq.onrender.com/dashboard",
	},
];
